apiVersion: v1
kind: ConfigMap
metadata:
  name: downlogger-config
  namespace: downlogger-prod
data:
  PORT: "3000"
  DB_HOST: "dbdevazureadmin-prod-db.ihme.washington.edu"
  DB_PORT: "3306"
  DB_NAME: "download_tracking"

